# Base configs
baseurl: "https://beestertime.github.io/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by beestertime"
header:
 title: "Photography"
 bio: "update later"
