# Base configs
baseurl: "https://beestertime.github.io/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by beestertime"
subtitle: "See the world through my eyes!"
header:
 title: "Photography"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
web_design: "AJ"
